

HEADERS:=$(shell find src -type f -name '*.h')

all: | clean configure build

clean:
	@rm -rf bin build
	@rm -f $(shell grep -ls '// Generated by dia2code' main.h ${HEADERS})

distclean: clean
	@rm -rf bin

configure:
	@mkdir -p build 
	@cd build && cmake ..

build: bin/client 

bin/client:
	@make -s -j4 -C build client

bin/server:
	@make -s -j4 -C build server

.PHONY: configure build clean
